org.gradle.jvmargs=-Xmx4096m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

minecraft_version=26.1.2
architectury_api_version=19.0.1
fabric_loader_version=0.18.4
fabric_api_version=0.148.2+26.1.2
neoforge_version=26.1.2.48-beta

maven_group=com.qloak
base_version=1.0.0

java_version=25
