org.gradle.jvmargs=-Xmx4096m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

minecraft_version=1.21.1
architectury_api_version=13.0.8
fabric_loader_version=0.16.9
fabric_api_version=0.110.0+1.21.1
neoforge_version=21.1.80

maven_group=com.qloak
base_version=1.0.0

java_version=21
